name: Docker Image Build and Push

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run:
          docker login --username swissmarley --password ${{ secrets.GITHUB_TOKEN }}
          docker build . -t ghcr.io/swissmarley/openai-suite:latest
          docker push ghcr.io/swissmarley/openai-suite:latest
