name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/swissmarley/openai-suite:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/swissmarley/openai-suite:latest
